c23319_g18/academia/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views



urlpatterns = [
    path('academia/', login_required(views.index), name='index'),
    path('informes', views.informes, name='informes'),
    path('alumnos/', login_required(views.alumnos), name='alumnos'),
    path('edita/<int:id>', views.alumnoedit, name='edita'),
    path('profesores/', views.profesores, name='profesores'),
    path('editp/<int:id>', views.profesoredit, name='editp'),
    path('aulas', views.aulas, name='aulas'),
    path('editau/<int:id>', views.aulasedit, name='editau'),
    path('materias', views.materias, name='materias'),
    path('editm/<int:id>', views.materiasedit, name='editm'),
    path('formulario/', views.formulario_view, name='formulario'),
    path('editaform/<int:id>', views.editar_formulario, name='editaform'),
]  

c23319_g18/c23319_g18/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from gestion_usuarios.views import LoginView, LogoutView
from .views import home



urlpatterns = [

    path('', home, name='login'),
    path('gestion_usuarios/', include('gestion_usuarios.urls'),name='gestion_usuarios'),
    path('gestion_usuarios/login/', LoginView.as_view(), name='login'),
    path("academia/", include("academia.urls"),name='academia'),
    path('', include("academia.urls")),
    path('email_reseteo_2/', include('email_reseteo_2.urls')),
    path('admin/', admin.site.urls,name='admin'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

c23319_g18/email_reseteo_2/urls.py
from django.urls import path
from . import views
from .views import EmailPasswordResetCompleteView
app_name = 'email_reseteo_2'

urlpatterns = [
    path('reset_password/', views.resetear_password, name='resetear_password'),
    path('reset_password/<str:token>/<str:user_email>/', views.resetear_password_confirm, name='resetear_password_confirm'),
    path('password_reset/done/', views.resetear_password_done, name='resetear_password_done'),
    path('reset/done/', EmailPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #path('perfil/', views.profile, name='profile'),
]

c23319_g18/gestion_usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import  CambiarPasswordDoneView, LoginView, LogoutView, CambiarPasswordView
from django.contrib import admin
from . import views

app_name = 'gestion_usuarios'

urlpatterns = [
    
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', views.signup , name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cambiar_password/', CambiarPasswordView.as_view(), name='cambiar_password'),
    path('cambiar_password/done/', CambiarPasswordDoneView.as_view(), name='cambiar_password_done'),
    path('academia/', include('academia.urls'), name='index'), # redirección a la app academia
]

handler404 = "gestion_usuarios.views.page_not_found_view"

c23319_g18/gestion_usuarios/models.py
# from django.db import models

# # Create your models here.
# from django.db import models
# from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# class UsuarioManager(BaseUserManager):
#     def create_user(self, nombre, apellido, email, password=None, tipo=None):
#         if not email:
#             raise ValueError('El usuario debe tener una dirección de email válida.')
#         usuario = self.model(
#             nombre=nombre,
#             apellido=apellido,
#             email=self.normalize_email(email),
#             tipo=tipo,
#         )
#         usuario.set_password(password)
#         usuario.save(using=self._db)
#         return usuario

#     def create_superuser(self, nombre, apellido, email, password=None):
#         usuario = self.create_user(
#             nombre=nombre,
#             apellido=apellido,
#             email=email,
#             password=password,
#             tipo='administrador',
#         )
#         usuario.is_admin = True
#         usuario.save(using=self._db)
#         return usuario

# class Usuario(AbstractBaseUser):
#     nombre = models.CharField(max_length=50)
#     apellido = models.CharField(max_length=50)
#     email = models.EmailField(unique=True)
#     tipo = models.CharField(max_length=20, choices=(('docente', 'Docente'), ('alumno', 'Alumno'), ('administrador', 'Administrador')))
#     is_active = models.BooleanField(default=True)
#     is_admin = models.BooleanField(default=False)

#     objects = UsuarioManager()

#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = ['nombre', 'apellido']

#     def __str__(self):
#         return self.email

#     @property
#     def is_staff(self):
#         return self.is_admin

c23319_g18/gestion_usuarios/forms.py
from django import forms
from django.contrib.auth.forms import  SetPasswordForm, AuthenticationForm, UserCreationForm
from django.utils.translation import gettext as _
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label='Nombre de usuario'
    )
    password1 = forms.CharField(
        min_length=4,
        max_length=50,
        widget=forms.PasswordInput(),
        label="Contraseña"
    )
    password2 = forms.CharField(
        min_length=4,
        max_length=50,
        widget=forms.PasswordInput(),
        label='Confirmar contraseña'
    )
    first_name = forms.CharField(
    min_length=2,
    max_length=50,
    label='Nombre'
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=50,
        label='Apellido'
    )
    email = forms.CharField(
        widget=forms.EmailInput(),
        label='Email'
    )
    
    def clean_username(self):
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            self.add_error('username', 'El nombre de usuario ya esta en uso.')
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('El email ya esta en uso.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
           raise forms.ValidationError('Las contraseñas no coinciden.')
        return password2
    
    def save(self,commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'first_name','last_name', 'email', 'password1', 'password2')


class CustomCambiarPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)



class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)

c23319_g18/gestion_usuarios/views.py
from typing import Any
from django.shortcuts import render

# Create your views here.
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import FormView, View
from django.views.generic.base import TemplateView
from .forms import  CustomSetPasswordForm, CustomAuthenticationForm, CustomCambiarPasswordForm, SignUpForm
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth import password_validation, authenticate, login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect


def signup(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            form.save()
            messages.success(request, 'Registro exitoso para ' + username)
            # new_user = authenticate(username=username, password=password)
            # if new_user is not None:
            #     login(request, new_user)
            return redirect('login')
    return render(request, 'gestion_usuarios/signup.html',{'form':form})

class LoginView(FormView):
    template_name = 'gestion_usuarios/login.html'
    form_class = CustomAuthenticationForm
    success_url = reverse_lazy('index')

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginView,self).dispatch(request, *args, **kwargs)
        
    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            messages.error(self.request, 'La combinación de usuario y contraseña no coinciden')
            return super().form_invalid(form)

@method_decorator(login_required, name='dispatch')
class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('login')

@method_decorator(login_required, name='dispatch')
class CambiarPasswordView(LoginRequiredMixin, PasswordChangeView):
    form_class = CustomCambiarPasswordForm
    success_url = reverse_lazy('gestion_usuarios:cambiar_password_done')
    template_name = 'gestion_usuarios/cambiar_password.html'
    extra_context = {'password_form': CustomSetPasswordForm(user=None)}
    
@method_decorator(login_required, name='dispatch')
class CambiarPasswordDoneView(TemplateView):
    template_name = 'gestion_usuarios/cambiar_password_done.html'
    success_url = reverse_lazy('gestion_usuarios:cambiar_password_done')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        context['login_url'] = reverse_lazy('login')
        return context

def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

c23319_g18/templates/gestion_usuarios/cambiar_password.html
{% extends 'layout.html' %} {% load widget_tweaks %}

{% block head %}
    
    
{% endblock %}

{% block body %}
<div class="container-fluid py-5">
  <div class="row justify-content-center">
    <div class="card bg-light">
      <div class="card-body">
<h2>Cambiar contraseña</h2>
<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="new_password1"
      ><strong>{{ form.new_password1.label_tag }}</strong></label
    >
    {% render_field form.new_password1 class="form-control" %}
  </div>
  <div class="form-group">
    <label for="new_password2"
      ><strong>{{ form.new_password2.label_tag }}</strong></label
    >
    {% render_field form.new_password2 class="form-control" %}
  </div>
  <button type="submit" class="btn btn-primary btn-block">Cambiar contraseña</button>
</form>
{% endblock %}

{% comment %} {% extends 'layout.html' %}

{% block body %}
<h2>Cambiar contraseña</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Cambiar contraseña</button>
</form>
{% endblock %} {% endcomment %}

c23319_g18/templates/gestion_usuarios/cambiar_password_done.html
{% extends 'layout2.html' %}

{% block head %}
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.6.0/cyborg/bootstrap.min.css">
{% endblock %}

{% block body %}
    <h1>Cambio de contraseña exitoso</h1>
    <p>Tu contraseña ha sido cambiada con éxito. Por favor, inicia sesión con tu nueva contraseña.</p>
    <a href="{{ login_url }}"class="btn btn-primary">Iniciar sesión</a>

{% endblock %}

{% comment %} {% extends 'layout2.html' %}

{% block body %}
    <h1>Cambio de contraseña exitoso</h1>
    <p>Tu contraseña ha sido cambiada con éxito. Por favor, inicia sesión con tu nueva contraseña.</p>
    <a href="{{ login_url }}">Iniciar sesión</a>

{% endblock %} {% endcomment %}

c23319_g18/templates/gestion_usuarios/login.html
{% extends 'layout2.html' %} {% load static %} {% load widget_tweaks %} {% block body %}
<body style="background-image: url('{%static 'images/school-design.jpg' %}');">
<div class="container-fluid py-5">
  <div class="row justify-content-center">
    <div class="card bg-light">
        
      <div class="card-body">
        <h2><i class="fa-solid fa-graduation-cap"></i> SIGA - Inicio de sesión</h2>

        {% if form.errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-bs-dismiss="alert">&times;</button>
          <strong>El usuario y/o la contraseña son incorrectos.</strong>
        </div>
        {% endif %}

        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <strong>{{message}}</strong> Inicie sesión
        </div>
        {% endfor %}
       
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="username"
              ><strong>{{ form.username.label_tag }}</strong></label
            >
            {% render_field form.username class="form-control" %}
          </div>
          <div class="form-group">
            <label for="username"
              ><strong>{{ form.password.label_tag }}</strong></label
            >
            {% render_field form.password class="form-control" %}
          </div>
          <div class="row justify-content-center">
            <button type="submit" class="btn btn-lg btn-primary">
              <i class="bi bi-box-arrow-in-right"></i> Iniciar sesión
            </button>
          </div>
        </form>
        <p class="py-2">
          <a href="{% url 'email_reseteo_2:resetear_password' %}"
            >¿Olvidaste tu contraseña?</a
          >
        </p>
        <p class="">¿Todavía no creaste tu cuenta?
          <a href="{% url 'gestion_usuarios:signup' %}"
            >Registrate</a
          >
        </p>

      </div>
    </div>
  </div>
</div>
{% endblock %} {% comment %} {% extends 'layout2.html' %} {% block body %}
<div class="col-md-6 mx-auto">
  <h2>S.I.G.A. - Inicio de sesión</h2>
  {% if form.errors %}
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-bs-dismiss="alert">&times;</button>
    <strong>Usuario y/o contraseña incorrectos.</strong>
  </div>
  {% endif %}
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Iniciar sesión</button>
  </form>
  <p><a href="{% url 'password_reset' %}">¿Olvidó su contraseña?</a></p>
</div>
{% endblock %} {% endcomment %}

c23319_g18/templates/gestion_usuarios/logout.html
{% extends 'layout2.html' %}

{% block body %}
<h2>Cierre de sesión</h2>
<p>Hasta luego, {{ request.user.username }}.</p>
<form method="post" action="{% url 'login' %}">
  {% csrf_token %}
  <button type="submit">Iniciar sesión nuevamente</button>
</form>
{% endblock %}

c23319_g18/templates/gestion_usuarios/signup.html
{% extends 'layout2.html' %} {% load static %} {% load widget_tweaks %} {% block body %}
<body style="background-image: url('{%static 'images/school-design.jpg' %}')">
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="card bg-light">
        <div class="card-body">
          <h2>
            <i class="fa-solid fa-graduation-cap"></i> SIGA - Registro de
            Usuario
          </h2>

          <!-- {% for error in field.errors %}
            {{ error }}
          {% endfor %} -->
          
          <!-- {% for message in messages %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-bs-dismiss="alert">&times;</button>
            <strong>{{ menssage }}</strong>
          </div>
          {% endfor %} -->

          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="username"
                ><strong>{{ form.username.label_tag }}</strong></label
              >
              {% render_field form.username class="form-control" %}
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="first_name"
                  ><strong>{{ form.first_name.label_tag }}</strong></label
                >
                {% render_field form.first_name class="form-control" %}
              </div>
              <div class="form-group col-md-6">
                <label for="last_name"
                  ><strong>{{ form.last_name.label_tag }}</strong></label
                >
                {% render_field form.last_name class="form-control" %}
              </div>
            </div>
            <div class="form-group">
              <label for="email"
                ><strong>{{ form.email.label_tag }}</strong></label
              >
              {% render_field form.email class="form-control" %}
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="password1"
                  ><strong>{{ form.password1.label_tag }}</strong></label
                >
                {% render_field form.password1 class="form-control" %}
              </div>
              <div class="form-group col-md-6">
                <label for="password2"
                  ><strong>{{ form.password2.label_tag }}</strong></label
                >
                {% render_field form.password2 class="form-control" %}
              </div>
            </div>
            <div class="row justify-content-center">
              <button type="submit" class="btn btn-lg btn-primary">
                <i class="bi bi-person-plus-fill"></i> Crear cuenta
              </button>
            </div>
          </form>
          <p class="py-2">
            ¿Ya estás registrado?
            <a href="{% url 'gestion_usuarios:login' %}">Ingresar</a>
          </p>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}