c23319_g18/academia/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views



urlpatterns = [
    path('academia/', login_required(views.index), name='index'),
    path('informes', views.informes, name='informes'),
    path('alumnos/', login_required(views.alumnos), name='alumnos'),
    path('edita/<int:id>', views.alumnoedit, name='edita'),
    path('profesores/', views.profesores, name='profesores'),
    path('editp/<int:id>', views.profesoredit, name='editp'),
    path('aulas', views.aulas, name='aulas'),
    path('editau/<int:id>', views.aulasedit, name='editau'),
    path('materias', views.materias, name='materias'),
    path('editm/<int:id>', views.materiasedit, name='editm'),
    path('formulario/', views.formulario_view, name='formulario'),
    path('editaform/<int:id>', views.editar_formulario, name='editaform'),
]  

c23319_g18/c23319_g18/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from gestion_usuarios.views import LoginView, LogoutView
from .views import home



urlpatterns = [

    path('', home, name='login'),
    path('gestion_usuarios/', include('gestion_usuarios.urls'),name='gestion_usuarios'),
    path('gestion_usuarios/login/', LoginView.as_view(), name='login'),
    path("academia/", include("academia.urls"),name='academia'),
    path('', include("academia.urls")),
    path('email_reseteo_2/', include('email_reseteo_2.urls')),
    path('admin/', admin.site.urls,name='admin'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

c23319_g18/gestion_usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import  CambiarPasswordDoneView, LoginView, LogoutView, CambiarPasswordView
from django.contrib import admin
from . import views

app_name = 'gestion_usuarios'

urlpatterns = [
    
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', views.signup , name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cambiar_password/', CambiarPasswordView.as_view(), name='cambiar_password'),
    path('cambiar_password/done/', CambiarPasswordDoneView.as_view(), name='cambiar_password_done'),
    path('academia/', include('academia.urls'), name='index'), # redirección a la app academia
]

handler404 = "gestion_usuarios.views.page_not_found_view"

c23319_g18/academia/models.py
from django.db import models
from django import forms


class Alumno(models.Model):
    id_alumno = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=75)
    apellido = models.CharField(max_length=75)
    nro_doc = models.CharField(max_length=15)
    foto = models.ImageField(upload_to='images/alumnos', null=True)
    fec_nacimiento = models.CharField(max_length=10)
    id_provincia = models.ForeignKey('Provincia', models.DO_NOTHING, db_column='id_provincia', default=1)
    id_pais = models.ForeignKey('Pais', models.DO_NOTHING, db_column='id_pais', default=1)
    nro_tel = models.CharField(max_length=75)
    correo = models.CharField(max_length=100)
    fec_inicio = models.CharField(max_length=10)
    clases = models.ManyToManyField('Clase', through='AlumnoClase')
    activo = models.BooleanField(blank=True, null=True)  # This field type is a guess.
    
    class Meta:
        managed = False
        db_table = 'alumno'

    def __str__(self):
        return str(self.nombre + ' ' + self.apellido)


class Clase(models.Model):
    id_clase = models.AutoField(primary_key=True)
    clase = models.CharField(max_length=35, blank=True, null=True)
    periodo = models.IntegerField(blank=True, null=True)
    id_materia = models.ForeignKey('Materia', models.DO_NOTHING, db_column='id_materia')
    id_profesor = models.ForeignKey('Profesor', models.DO_NOTHING, db_column='id_profesor')
    capacidad = models.IntegerField(blank=True, null=True)
    alumnos = models.ManyToManyField('Alumno', through='AlumnoClase')

    class Meta:
        managed = False
        db_table = 'clase'
    
    def __str__(self):
        return str(self.clase)


class Materia(models.Model):
    id_materia = models.AutoField(primary_key=True)
    materia = models.CharField(max_length=35, blank=True, null=True)
    carrera = models.CharField(max_length=35, blank=True, null=True)
    anio = models.CharField(max_length=15, blank=True, null=True)
    cuatrimestre = models.CharField(max_length=15, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'materia'
    
    def __str__(self):
        return str(self.materia)


class Pais(models.Model):
    id_pais = models.AutoField(primary_key=True)
    iso = models.CharField(max_length=2, blank=True, null=True)
    desc_pais = models.CharField(max_length=75, blank=True, null=True)
    bandera = models.TextField(blank=True, null=True)
    numorden = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pais'
    
    def __str__(self):
        return str(self.desc_pais)



class Profesor(models.Model):
    id_profesor = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=75, blank=True, null=True)
    apellido = models.CharField(max_length=75, blank=True, null=True)
    nro_doc = models.CharField(max_length=15)
    foto = models.ImageField(upload_to='images/profesores', null=True)
    fec_nacimiento = models.CharField(max_length=10)
    id_provincia = models.ForeignKey('Provincia', models.DO_NOTHING, db_column='id_provincia', default=1)
    id_pais = models.ForeignKey(Pais, models.DO_NOTHING, db_column='id_pais', default=1)
    nro_tel = models.CharField(max_length=75)
    correo = models.CharField(max_length=100)
    fec_inicio = models.CharField(max_length=10)
    activo = models.BooleanField(blank=True, null=True)  # This field type is a guess.

    class Meta:
        managed = False
        db_table = 'profesor'

    
    def __str__(self):
        return str(self.nombre + ' ' + self.apellido )


class Provincia(models.Model):
    id_provincia = models.AutoField(primary_key=True)
    desc_provincia = models.CharField(max_length=35, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'provincia'
    
    def __str__(self):
        return str(self.desc_provincia)


class AlumnoClase(models.Model):
    alumno = models.ForeignKey(Alumno, models.DO_NOTHING, db_column='id_alumno')
    clase = models.ForeignKey(Clase, models.DO_NOTHING, db_column='id_clase')
    faltas = models.IntegerField()
    calificacion = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'alumno_clase'
    
    def __str__(self):
        return str(self.alumno )

c23319_g18/academia/forms.py
from django import forms
from .models import Alumno, Profesor, Materia, Clase, AlumnoClase

class Alumnoform(forms.ModelForm):
    class Meta:
        model = Alumno
        fields = ('nombre', 'apellido', 'nro_doc', 'nro_tel', 'correo', 'id_provincia', 'id_pais', 'fec_nacimiento', 'foto', 'fec_inicio', 'activo')

 
class Profesorform(forms.ModelForm):
    class Meta:
        model = Profesor
        fields = ('nombre', 'apellido', 'nro_doc', 'nro_tel', 'correo', 'id_provincia', 'id_pais', 'fec_nacimiento', 'foto', 'fec_inicio', 'activo')


class Materiaform(forms.ModelForm):
    class Meta:
        model = Materia
        fields = ('materia', 'carrera', 'anio', 'cuatrimestre')
        error_messages = {
            'materia' :{
                'required':'No te olvides de mi!'
            }
        }
class Claseform(forms.ModelForm):
    class Meta:
        model = Clase
        fields = ('id_clase', 'clase','periodo','id_materia','id_profesor','capacidad')
        error_messages = {
            'materia' :{
                'required':'No te olvides de mi!'
            }
        }  

class AlumnoClaseForm(forms.ModelForm):
    alumno = forms.ModelChoiceField(queryset=Alumno.objects.all())
    clases = forms.ModelMultipleChoiceField(queryset=Clase.objects.all(), widget=forms.CheckboxSelectMultiple)
    faltas = forms.IntegerField()
    calificacion = forms.IntegerField()
    class Meta:
        model = AlumnoClase
        fields = ('alumno', 'clases', 'faltas', 'calificacion')

c23319_g18/academia/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import Alumnoform, Profesorform, Materiaform, Claseform, AlumnoClaseForm
from .models import Materia, Alumno, Profesor, Clase, Pais, AlumnoClase


@login_required
def alumnos(request):
    if request.GET.get('tags') == None:
        alumnos = Alumno.objects.all().order_by('-id_alumno')[:8]
    else:
        param = '%' + str(request.GET.get('tags')) + '%'
        alumnos = Alumno.objects.extra(where=["nombre LIKE %s OR apellido LIKE %s"], params=[param, param]).order_by('-id_alumno')[:8]

    if request.method == 'GET':
        form = Alumnoform()
    else:
        form = Alumnoform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/alumnos')
    return render(request, "alumnos.html", {'alumnos':alumnos, 'form':form})

@login_required
def alumnoedit(request, id):
    
    if request.GET.get('tags') == None:
        alumnos = Alumno.objects.all().order_by('-id_alumno')[:8]
    else:
        param = '%' + str(request.GET.get('tags')) + '%'
        alumnos = Alumno.objects.extra(where=["nombre LIKE %s OR apellido LIKE %s"], params=[param, param]).order_by('-id_alumno')[:8]
  
    alumno = get_object_or_404(Alumno, id_alumno = id)
    country = Pais.objects.select_related().get(id_pais=alumno.id_pais.pk)

    if request.method == 'GET':
        form = Alumnoform(instance = alumno)
    else:
        form = Alumnoform(request.POST, request.FILES, instance = alumno)
        if form.is_valid():
            form.save()
            return redirect('/alumnos')
    return render(request, "alumnos.html", {'alumnos':alumnos, 'country':country, 'form':form})


@login_required
def profesores(request):
    if request.GET.get('tags') == None:
        profesores = Profesor.objects.all().order_by('-id_profesor')[:8]
    else:
        param = '%' + str(request.GET.get('tags')) + '%'
        profesores = Profesor.objects.extra(where=["nombre LIKE %s OR apellido LIKE %s"], params=[param, param]).order_by('-id_profesor')[:8]
  
    if request.method == 'GET':
        form = Profesorform()
    else:
        form = Profesorform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/profesores')
    return render(request, "profesores.html", {'profesores':profesores, 'form':form})

@login_required
def profesoredit(request, id):
    
    if request.GET.get('tags') == None:
        profesores = Profesor.objects.all().order_by('-id_profesor')[:8]
    else:
        param = '%' + str(request.GET.get('tags')) + '%'
        profesores = Profesor.objects.extra(where=["nombre LIKE %s OR apellido LIKE %s"], params=[param, param]).order_by('-id_profesor')[:8]
 
    
    profesor = Profesor.objects.get(id_profesor = id)
    country = Pais.objects.select_related().get(id_pais=profesor.id_pais.pk)

    if request.method == 'GET':
        form = Profesorform(instance = profesor)
    else:
        form = Profesorform(request.POST,request.FILES, instance = profesor)
        if form.is_valid():
            form.save()
            return redirect('/profesores')
    return render(request, "profesores.html", {'profesores':profesores, 'country':country, 'form':form})

@login_required
def aulas(request):
    items = Clase.objects.all().order_by('-id_clase')[:8]
   
    if request.method == 'GET':
        form = Claseform()
    else:
        form = Claseform(request.POST) 
        if form.is_valid():
            form.save()
            return redirect('/aulas')
        
    return render(request, "aulas.html", {'items':items, 'form':form})

@login_required
def aulasedit(request, id):

    if request.GET.get('tags') == None:
        items = Clase.objects.all().order_by('-id_clase')[:8]
    else:
        param = '%' + str(request.GET.get('tags')) + '%'
        items = Clase.objects.extra(where=[" clase LIKE %s"], params=[param]).order_by('-id_clase')[:8]
    
    clase = Clase.objects.get(id_clase = id)

    if request.method == 'GET':
        form = Claseform(instance = clase)
    else:
        form = Claseform(request.POST, instance = clase)
        if form.is_valid():
            form.save()
            return redirect('/aulas')
    return render(request, "aulas.html", {'items':items,  'form':form})
    

@login_required
def materias(request):
    if request.GET.get('tags') == None:
        items = Materia.objects.all().order_by('id_materia')[:8]
    else:
        param = '%' + str(request.GET.get('tags')) + '%'
        items = Materia.objects.extra(where=["carrera LIKE %s OR materia LIKE %s"], params=[param, param]).order_by('-id_materia')[:8]
    
    if request.method == 'GET':
        form = Materiaform()
    else:
        form = Materiaform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/materias')
        
    return render(request, "materias.html", {'items':items, 'form':form})

@login_required
def materiasedit(request, id):

    if request.GET.get('tags') == None:
        items = Materia.objects.all().order_by('id_materia')[:8]
    else:
        param = '%' + str(request.GET.get('tags')) + '%'
        items = Materia.objects.extra(where=["carrera LIKE %s OR materia LIKE %s"], params=[param, param]).order_by('-id_materia')[:8]
    
    materia = Materia.objects.get(id_materia = id)
    if request.method == 'GET':
        form = Materiaform(instance = materia)
    else:
        form = Materiaform(request.POST, instance = materia)
        if form.is_valid():
            form.save()
            return redirect('/materias')
    return render(request, "materias.html", {'items':items, 'form':form})

@login_required
def formulario_view(request):
    alumnos = Alumno.objects.all()
    clases = Clase.objects.all()
    alumno_clases = AlumnoClase.objects.all()

    # Obtener el parámetro de ordenamiento desde la URL
    sort_param = request.GET.get('sort')
    direction_param = request.GET.get('direction')
    default_direction = 'asc'
    if direction_param and direction_param.lower() == 'desc': 
        default_direction = 'desc'

    # Ordenar los registros
    if sort_param:
        if sort_param == 'alumno':
            alumno_clases = alumno_clases.order_by(f'alumno__apellido', f'alumno__nombre')
        elif sort_param == 'clases':
            alumno_clases = alumno_clases.order_by('clase__clase')
        elif sort_param == 'faltas':
            alumno_clases = alumno_clases.order_by('faltas')
        elif sort_param == 'calificacion':
            alumno_clases = alumno_clases.order_by('calificacion')

        # Invertir el orden si la dirección es descendente
        if default_direction == 'desc':
            alumno_clases = alumno_clases.reverse()
    
    if request.method == 'POST':
        alumno_id = request.POST.get('alumno')
        clase_ids = request.POST.getlist('clases')
        faltas = int(request.POST.get('faltas'))
        calificacion = int(request.POST.get('calificacion'))
        #materia_id = request.POST.get('materia')
        
        alumno = Alumno.objects.get(id_alumno=alumno_id)
        
        for clase_id in clase_ids:
            clase = Clase.objects.get(id_clase=clase_id)
            #materia = Materia.objects.get(id_materia=materia_id)
            AlumnoClase.objects.create(
                alumno=alumno, 
                clase=clase,
                #materia =materia,
                faltas=faltas,
                calificacion=calificacion
            )  
        
        return redirect('formulario')  
        
    context = {
        'alumnos': alumnos,
        'clases': clases,
        'items': alumno_clases,
        'direction': request.GET.get('direction')  # Pasar el parámetro 'direction' al contexto
    }
    
    return render(request, 'formulario.html', context)

@login_required
def editar_formulario(request, id):
    alumnos = Alumno.objects.all()
    clases = Clase.objects.all()
    alumno_clases = AlumnoClase.objects.all()

    registro = get_object_or_404(AlumnoClase, id=id)
    
    if request.method == 'GET':
        form = AlumnoClaseForm(instance=registro)
    else:
        form = AlumnoClaseForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            return redirect('formulario')
    
    context = {
        'alumnos': alumnos,
        'clases': clases,
        'items': alumno_clases,
        'form': form
    }
    
    return render(request, 'formulario.html', context)

@login_required
def calificaciones(request):
    return render(request, "calificaciones.html")

@login_required
def informes(request):
    return render(request, "informes.html")

@login_required
def index(request):
    return render(request, "nosotros.html")

c23319_g18/academia/templates/alumnos.html
{% extends "layout.html" %} {% load static %} {% load widget_tweaks %} {% block title %} SIGA - Alumnos
{% endblock %} {% block body %}

<div class="container-fluid py-2">
  <h4 class="display-5 fw-bold"><i class="bi bi-people-fill"></i> Alumnos</h4>
      <div class="row">
        <div accion="" class="col-md-8">
          <div class="card bg-light border-success">
            <div class="card-body">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

          <div class="form-group">
            <div class="row justify-content-center">
                {% if form.foto.value == NULL %}
                <img
                  class="img-maximo"
                  src='{% static "images/pna.jpg" %}'
                  alt="foto del alumno"
                />
                {% else %}
                {% if form.foto %}
                <img class="img-perfil-alumno" src ='/media/{{ form.foto.value }}' alt="foto del alumno">
                {% endif %}
                {% endif %}
            </div>
          </div>
            
            <div class="form-row">
              <div class="form-group col-md-5">
                <label for="nombre"><strong>Nombre</strong></label>
                {% render_field form.nombre class="form-control" %}
              </div>
              <div class="form-group col-md-5">
                <label for="apellido"><strong>Apellido</strong></label>
                {% render_field form.apellido class="form-control" %}
              </div>
              <div class="form-group col-md-2">
                <label for="nro_doc"><strong>Documento</strong></label>
                {% render_field form.nro_doc class="form-control" %}
              </div>
            </div>
          
            <div class="form-row">
              <div class="form-group col-md-3">
                <label for="fec_nacimiento"><strong>Fecha Nacimiento</strong></label>
                {% render_field form.fec_nacimiento type="date" class="form-control" %}
              </div>
              <div class="form-group col-md-4">
                <label for="nro_tel"><strong>Telefono</strong></label>
                {% render_field form.nro_tel class="form-control" %}
              </div>
              <div class="form-group col-md-5">
                <label for="correo"><strong>Email</strong></label>
                {% render_field form.correo type="email" class="form-control" %}
              </div>
            </div>

            <div class="form-row">

            </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="id_provincia"><strong>Provincia</strong></label>            
              {% render_field form.id_provincia class="form-control" %}
            </div>
            <div class="form-group col-md-5">
              <label for="id_pais"><strong>Pais</strong></label> 
              {% render_field form.id_pais class="form-control" %}
            </div>
            <div class="form-group col-md-3">
              <label for="fec_inicio"><strong>Fecha Ingreso</strong></label> 
              {% render_field form.fec_inicio type="date" class="form-control" %}
            </div>
          </div>

          <div class="row justify-content-end">
            <div class="col-md-10">
              {{ form.foto }}
            </div>
            <div class="col-md-2">
              {% if country.bandera != NULL %}
              <img class="img-fluid float-md-end" src ='/media/{{ country.bandera }}' alt="bandera">
              {% endif %}
            </div>
          </div>
            
          <div class="form-group" style="padding-top: 1px;">
            <div class="row justify-content-center">
              <div class="col-md-3">
                <button
                  type="reset"
                  onclick="window.location.href='/alumnos/'"
                  class="btn btn-lg btn-danger mx-auto d-block"
                title="Cancelar">
                  <i class="bi bi-x-circle"></i> Cancelar
                </button>
              </div>
              <div class="col-md-3">
              <button type="submit" class="btn btn-lg btn-success mx-auto d-block"><i class="bi bi-check-circle"></i>
                Guardar</button>
              </div>
            </div>
          </div>

          </form>
        </div>
        </div>
      
    </div>
    <div class="col-md-4">

      <div class="form-group py-2" style="float: right">
        <form class="d-flex" action="">
          <input type="text" class="form-control" placeholder="Buscar..." name="tags" id="tags">
        </form>
      </div>

      <table class="table table-bordered table-sm">
        <thead style="text-align: center">
          <tr>
            <th style="font-weight: bold">N° Mat.</th>
            <th style="font-weight: bold">Nombre</th>
            <th style="font-weight: bold">Apellido</th>
            <th style="font-weight: bold">Editar</th>
          </tr>
        </thead>
        <tbody>
          {% for alumno in alumnos %}
          <tr>
            <td style="text-align: center;">{{ alumno.id_alumno }}</td>
            <!--  -->
            <td>{{ alumno.nombre }}</td>
            <td>{{ alumno.apellido | upper }}</td>
            <!--  -->
            <td style="text-align: center">
              <a href="{% url 'edita' alumno.id_alumno %}" class="btn btn-outline-primary" title="Guardar">
                <i class="bi bi-pencil-square"></i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

c23319_g18/academia/templates/calificaciones.html
{% extends "layout.html" %} {% load static %} {% block title %} SIGA - Calificaciones
{% endblock %} {% block body %}

    <div class="container-fluid py-5">
      <h2 class="display-5 fw-bold">Calificaciones</h2>
    </div>
{% endblock %}

c23319_g18/academia/templates/informes.html
{% extends "layout.html" %} {% load static %} {% block title %} SIGA - Informes
{% endblock %} {% block body %}
<div class="container-fluid">
  <div class="container-fluid py-5">
    <h2 class="display-5 fw-bold">Informes</h2>
    <p class="col-md-12">
      Accede a informes y listados académicos con los que estar al día sobre
      todo lo que ocurre en tu centro.
    </p>
    <ul>
      <li>
        <h5>Listados</h5>
        <p>
          Crea listas en base a filtros detallados que muestra información
          actualizada.
        </p>
      </li>
      <li>
        <h5>Control de Entregas</h5>
        <p>
          Accede a informes detallados sobre las entregas programadas en cada
          aula.
        </p>
      </li>
      <li>
        <h5>Progreso del Aula</h5>
        <p>
          Visualiza el porcentaje de entregas realizadas en cada aula y
          progresión de los alumnos.
        </p>
      </li>
    </ul>
  </div>
</div>
{% endblock %}

c23319_g18/academia/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>{% block title %} {% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS v5.2.1 -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link
      rel="stylesheet"
      href="https://bootswatch.com/4/sandstone/bootstrap.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light justify-content-end">
            <ul class="nav navbar-nav">
                <a class="navbar-brand mt-2 mt-lg-0" href="/">
                  <i class="fa-solid fa-graduation-cap"></i>
                </a>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    data-bs-toggle="dropdown"
                    href="#"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Gestión Academica</a
                  >
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'alumnos' %}"><i class="bi bi-people-fill"></i> Alumnos</a>
                    <a class="dropdown-item" href="{% url 'profesores' %}"
                      ><i class="bi bi-person-video3"></i> Profesores</a
                    >
                    <a class="dropdown-item" href="{% url 'materias' %}"
                      ><i class="bi bi-book"></i> Materias</a
                    >
                    <a class="dropdown-item" href="{% url 'aulas' %}"><i class="bi bi-door-open"></i> Aulas</a>
                    <a class="dropdown-item" href="{% url 'formulario' %}"
                      ><i class="bi bi-calendar-week"></i> Registro</a
                    >
                  </div>
                </li>
              </ul>
              <ul class="nav navbar-nav">
                <li class="nav-item dropdown">
                    <a
                      class="nav-link dropdown-toggle"
                      data-bs-toggle="dropdown"
                      href="#"
                      role="button"
                      aria-haspopup="true"
                      aria-expanded="false"
                      >Mi cuenta</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'gestion_usuarios:cambiar_password' %}"><i class="bi bi-braces-asterisk"></i> Cambiar Contraseña</a>
                      <a class="dropdown-item" href="{% url 'admin:index' %}"><i class="bi bi-gear-fill"></i> Administracion</a>
                    </div>
                  </li>
                </ul>
            <button class="btn btn-outline-primary ml-auto"> <i class="bi bi-person-circle"></i> {{ user.first_name }} {{ user.last_name }} ({{user.username}})</button>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
              <a class="dropdown-item" href="{% url 'gestion_usuarios:logout' %}"><i class="bi bi-arrow-right-circle-fill"></i> Log Out</a>
            </div>
        </nav>

    </header>
    <div class="container">
      <div class="row">
        <div class="col-12">{% block body %} {% endblock %}</div>
      </div>
    </div>
    <footer>
      <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
      integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/c4476a7d86.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>